# Generated by Django 5.2.8 on 2025-11-23 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_photos/clients/')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='documents/clients/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('professional_email', models.EmailField(max_length=254)),
                ('service_address', models.TextField(blank=True)),
                ('technical_qualification', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_photos/providers/')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='documents/providers/identity/')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='documents/providers/certifications/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Foto do portfólio', upload_to='portfolio/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('desired_datetime', models.DateTimeField(blank=True, null=True)),
                ('proposed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('completed', 'Concluído')], default='pending', max_length=20)),
                ('completed_by_client', models.BooleanField(default=False)),
                ('completed_by_provider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating', models.IntegerField(blank=True, help_text='Avaliação do cliente (0-5 estrelas)', null=True)),
                ('client_comment', models.TextField(blank=True, help_text='Comentário do cliente')),
                ('client_photo', models.ImageField(blank=True, help_text='Foto do trabalho realizado', null=True, upload_to='review_photos/')),
                ('client_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_rating', models.IntegerField(blank=True, help_text='Avaliação do prestador (0-5 estrelas)', null=True)),
                ('provider_comment', models.TextField(blank=True, help_text='Comentário do prestador')),
                ('provider_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
