# Generated by Django 5.2.7 on 2025-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_city_clientprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
