# Generated by Django 5.2.8 on 2025-11-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_servicerequest_completed_by_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating', models.IntegerField(blank=True, help_text='Avaliação do cliente (0-5 estrelas)', null=True)),
                ('client_comment', models.TextField(blank=True, help_text='Comentário do cliente')),
                ('client_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_rating', models.IntegerField(blank=True, help_text='Avaliação do prestador (0-5 estrelas)', null=True)),
                ('provider_comment', models.TextField(blank=True, help_text='Comentário do prestador')),
                ('provider_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.servicerequest')),
            ],
        ),
    ]
