# Generated by Django 5.2.8 on 2025-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_photos/clients/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_photos/providers/'),
        ),
        migrations.AddField(
            model_name='review',
            name='client_photo',
            field=models.ImageField(blank=True, help_text='Foto do trabalho realizado', null=True, upload_to='review_photos/'),
        ),
    ]
