"""
Django settings for fazpramim project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^hj)fd7_#-*(5zg821(6ivuv1)5&$vt49u83(&xbquinz3ln!q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # Em desenvolvimento pode deixar assim


# ------------------------
# APPLICATIONS
# ------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'fazpramim',

    'rest_framework',
    'corsheaders',
    'knox'
]


# ------------------------
# MIDDLEWARE (corrigido)
# ------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # CORS deve vir logo depois de SecurityMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ------------------------
# URL / WSGI
# ------------------------

ROOT_URLCONF = 'fazpramim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fazpramim.wsgi.application'


# ------------------------
# DATABASE
# ------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------------
# PASSWORD VALIDATION
# ------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------
# INTERNATIONALIZATION
# ------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ------------------------
# STATIC & MEDIA
# ------------------------

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ------------------------
# CORS / CSRF (corrigido)
# ------------------------

# Permitir requisições de QUALQUER origem (apenas DEV)
CORS_ALLOW_ALL_ORIGINS = True

# Para aceitar POST/PUT/DELETE vindos de fora
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "https://fazpramim-front.onrender.com",
   
]

# Para permitir cookies de frontend externo
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SAMESITE = None

CSRF_COOKIE_SECURE = False   # Em produção → True
SESSION_COOKIE_SECURE = False


# ------------------------
# DEFAULTS
# ------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------
# API CONFIGURATION (DRF / KNOX)
# ------------------------

REST_FRAMEWORK = {
    # Define o Knox como o sistema de autenticação padrão para a API
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
    ),
    # Define a permissão padrão como exigindo autenticação
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Configuração opcional para renderizadores e parsers
    # 'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',),
    # 'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
}

# Configurações do Knox (Opcional, mas útil)
# Define por quanto tempo o token será válido (ex: 24 horas)
REST_KNOX = {
    'TOKEN_TTL': None,  # Exemplo: datetime.timedelta(hours=24) ou None para tokens de longa duração
    'TOKEN_LIMIT_PER_USER': None, # Limite o número de tokens ativos por usuário (Ex: 3)
}